# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlcomix_ui.ui'
#
# Created: Tue Mar  8 16:21:15 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DLComix(object):
    def setupUi(self, DLComix):
        DLComix.setObjectName("DLComix")
        DLComix.resize(824, 468)
        self.centralwidget = QtGui.QWidget(DLComix)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 231, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 231, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(330, 0, 501, 421))
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(60, 110, 301, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.comboBox.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox.setEditable(False)
        self.comboBox.setMaxCount(20000)
        self.comboBox.setObjectName("comboBox")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(50, 30, 104, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 60, 70, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(50, 170, 271, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 200, 281, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 230, 251, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setEnabled(True)
        self.spinBox.setGeometry(QtCore.QRect(50, 260, 53, 25))
        self.spinBox.setReadOnly(False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(150, 265, 131, 16))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 330, 88, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 140, 481, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 300, 481, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 210, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        DLComix.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DLComix)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 23))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdition = QtGui.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        DLComix.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DLComix)
        self.statusbar.setObjectName("statusbar")
        DLComix.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(DLComix)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionPreferences = QtGui.QAction(DLComix)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionA_Propos = QtGui.QAction(DLComix)
        self.actionA_Propos.setObjectName("actionA_Propos")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuEdition.addAction(self.actionPreferences)
        self.menuAide.addAction(self.actionA_Propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(DLComix)
        QtCore.QMetaObject.connectSlotsByName(DLComix)

    def retranslateUi(self, DLComix):
        DLComix.setWindowTitle(QtGui.QApplication.translate("DLComix", "DLComix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DLComix", "Mettre à jour la base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("DLComix", "Télécharger selon les préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DLComix", "Choix du manga ou comic", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("DLComix", "Comic", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("DLComix", "Manga", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("DLComix", "Téléchargement intégral", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("DLComix", "Créer des archives", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("DLComix", "Optimiser le nom des archives", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DLComix", "Limite de transfert", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("DLComix", "Télécharger", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("DLComix", "Réinitaliser", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("DLComix", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdition.setTitle(QtGui.QApplication.translate("DLComix", "Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("DLComix", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("DLComix", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("DLComix", "Préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA_Propos.setText(QtGui.QApplication.translate("DLComix", "A Propos", None, QtGui.QApplication.UnicodeUTF8))

